name: stride
description: "A Flutter step tracker app."
publish_to: 'none'

version: 4.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core & UI
  pedometer: ^4.1.1
  percent_indicator: ^4.2.3
  intl: ^0.18.1

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Charts
  fl_chart: ^0.63.0

  # Permissions
  permission_handler: ^11.3.1
  url_launcher: ^6.2.6

  # State Management
  provider: ^6.1.5

  # Background Service
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2

  # Notifications
  flutter_local_notifications: ^18.0.1

  # Sharing & Export
  share_plus: ^10.1.4
  path_provider: ^2.1.5
  csv: ^6.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # Icon Generator
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/
