name: stride
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core & UI
  pedometer: ^4.1.1
  percent_indicator: ^4.2.3
  intl: ^0.18.1
  
  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Charts
  fl_chart: ^0.63.0

  # Permissions
  permission_handler: ^11.3.1
  url_launcher: ^6.2.6

  cupertino_icons: ^1.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # Icon Generator
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# Icon Generator Config
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png" # <-- IMPORTANT: Change "logo.png" to your file name
  min_sdk_android: 21